### ISSUE TITLE
cpe_chrome is broken on chef 16

### ISSUE THREAD

**Issue by erikng** [facebook/IT-CPE#243] opened 2020-05-18 21:27 UTC
-->

## Description
on Linux and macOS, cpe_chrome always returns with zero resources. This is because the resource names are identical for both windows/non-windows.

Chef 16 looks to not handle that any longer.

## Chef Version
Chef 16.1

## Platform Version
macOS/Linux

## Replication Case
Run chef, notice that the profiles get removed.

## Client Output
Not needed

## how to fix
change `cpe_chrome/recipes/default.rb`

```
if node.windows?
  cpe_chrome_win 'Configure Google Chrome'
else
  cpe_chrome 'Configure Google Chrome'
end
```

change `cpe_chrome/resources/cpe_chrome_win.rb`

```
resource_name :cpe_chrome_win
provides :cpe_chrome, :os => 'windows'
default_action :config
```

**Comment by mikedodge04** [comment] 2020-05-19 02:19
That cant be true. Then none of the bulit in resources would would. EX:
file, package, user

How were you able to re-pro ?

**Comment by erikng** [comment] 2020-05-19 02:29
By running chef lol. Try it out :)

Thanks,
Erik Gomez
________________________________

**Comment by btm** [comment] 2020-05-19 20:28
Chef 16.0.287, current head of this repo (5e0bce5876e88faeb8a4d272566d2627af4423db), Windows 10. The cpe_chrome cookbook doesn't appear to have any issues for me.

Having a better example of a reproduction would be helpful.

```
PS C:\Users\btm\Documents\IT-CPE\itchef> cat .\chrome.json
{
        "cpe_chrome": {
                "mp": {
                        "FileContents": {
                                "first_run_tabs": [
                                        "https://www.facebook.com"
                                ]
                        }
                }
        }
}
PS C:\Users\btm\Documents\IT-CPE\itchef> chef-client -z -o cpe_chrome -j chrome.json
[2020-05-19T20:21:52+00:00] WARN: No config file found or specified on command line. Using command line options instead.
Starting Chef Infra Client, version 16.0.287
[2020-05-19T20:22:06+00:00] WARN: Run List override has been provided.
[2020-05-19T20:22:06+00:00] WARN: Overridden Run List: [recipe[cpe_chrome]]
resolving cookbooks for run list: ["cpe_chrome"]
Synchronizing Cookbooks:
  - cpe_profiles (0.1.0)
  - cpe_chrome (0.1.0)
  - cpe_helpers (0.1.0)
  - fb_helpers (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: cpe_chrome::default
  * cpe_chrome[Configure Google Chrome] action config[2020-05-19T20:22:07+00:00] WARN: TotalMemoryLimitMb is not a supported setting

    * registry_key[HKLM\Software\Policies\Google\Chrome\AutoplayWhitelist] action delete_key (up to date)
    * registry_key[HKLM\Software\Policies\Google\Chrome\AutoplayWhitelist] action create (skipped due to not_if)
    * registry_key[HKLM\Software\Policies\Google\Chrome\ExtensionInstallForcelist] action delete_key (up to date)
    * registry_key[HKLM\Software\Policies\Google\Chrome\ExtensionInstallForcelist] action create (skipped due to not_if)
    * registry_key[HKLM\Software\Policies\Google\Chrome\ExtensionInstallBlacklist] action delete_key (up to date)
    * registry_key[HKLM\Software\Policies\Google\Chrome\ExtensionInstallBlacklist] action create (skipped due to not_if)
    * registry_key[HKLM\Software\Policies\Google\Chrome\DefaultPluginsSetting] action delete_key
      - delete key HKLM\Software\Policies\Google\Chrome\DefaultPluginsSetting
    * registry_key[HKLM\Software\Policies\Google\Chrome\DefaultPluginsSetting] action create
      - create key HKLM\Software\Policies\Google\Chrome\DefaultPluginsSetting
      - set value {:name=>"DefaultPluginsSetting", :type=>:dword, :data=>nil}
    * registry_key[HKLM\Software\Policies\Google\Chrome\ExtensionInstallSources] action delete_key (up to date)
    * registry_key[HKLM\Software\Policies\Google\Chrome\ExtensionInstallSources] action create (skipped due to not_if)
    * registry_key[HKLM\Software\Policies\Google\Chrome\PluginsAllowedForUrls] action delete_key (up to date)
    * registry_key[HKLM\Software\Policies\Google\Chrome\PluginsAllowedForUrls] action create (skipped due to not_if)
    * registry_key[HKLM\Software\Policies\Google\Chrome\RelaunchNotification] action delete_key
      - delete key HKLM\Software\Policies\Google\Chrome\RelaunchNotification
    * registry_key[HKLM\Software\Policies\Google\Chrome\RelaunchNotification] action create
      - create key HKLM\Software\Policies\Google\Chrome\RelaunchNotification
      - set value {:name=>"RelaunchNotification", :type=>:dword, :data=>nil}
    * registry_key[HKLM\Software\Policies\Google\Chrome\RelaunchNotificationPeriod] action delete_key
      - delete key HKLM\Software\Policies\Google\Chrome\RelaunchNotificationPeriod
    * registry_key[HKLM\Software\Policies\Google\Chrome\RelaunchNotificationPeriod] action create
      - create key HKLM\Software\Policies\Google\Chrome\RelaunchNotificationPeriod
      - set value {:name=>"RelaunchNotificationPeriod", :type=>:dword, :data=>nil}
    * file[delete-c:\Program Files (x86)\Google\Chrome\Application\master_preferences] action delete (skipped due to only_if)
    * directory[C:\Program Files (x86)\Google] action create (up to date)
    * directory[C:\Program Files (x86)\Google\Chrome] action create (up to date)
    * directory[C:\Program Files (x86)\Google\Chrome\Application] action create (up to date)
    * file[create-c:\Program Files (x86)\Google\Chrome\Application\master_preferences] action create (up to date)

[2020-05-19T20:22:07+00:00] WARN: Skipping final node save because override_runlist was given

Running handlers:
Running handlers complete
Chef Infra Client finished, 7/22 resources updated in 09 seconds

```

**Comment by steelcowboy** [comment] 2020-05-19 22:51
You can follow along at https://github.com/chef/chef/issues/9885 for the root cause, but the tl;dr is that Chef would silently determine what resource it should be loading, but [when that went away](https://github.com/chef/chef/pull/9441) it defaulted to using the Windows resource. As such, the reason why you saw nothing on Linux and MacOS was that the Windows resource was sanely returning since it wasn't running on WIndows :)

I think by simply renaming the resource to `cpe_chrome_win` the collision is gone, it's correctly determining the resource through `provides`, and this issue should be solved! Please let me know if you're still having problems and we can look into it, otherwise closing this out.

Thank you so much for bringing this to our attention, helping us get rid of this issue in a few other places too!

**Closed by steelcowboy** 2020-05-19 22:51 UTC

**Comment by erikng** [comment] 2020-05-20 00:18
Sweet, I'll backport this fix as well. Glad you were able to replicate it.

**Comment by btm** [comment] 2020-05-20 12:00
@steelcowboy as I mentioned [over on this commit](https://github.com/facebook/IT-CPE/commit/5218f618d9d6b7ca4e8439dc4e414e8092eafcfc#commitcomment-39293782), I recommend leaving the resources with the same name, but the linux version needs a `provides` line added to it.

This makes it easier on the user, you don't have to figure out and remember if it is cpe_chrome_win or cpe_chrome_linux or cpe_chrome or win_cpe_chrome or any other combination. You *can* have multiple resources with the same name (even on Chef 16) but chef needs the provides line to figure out which one to use.

**Comment by erikng** [comment] 2020-05-20 14:51
Interesting because even with the provides, it did not work for me on Darwin.

Thanks,
Erik Gomez
________________________________

**Comment by michel-slm** [comment] 2020-05-20 17:41
> @steelcowboy as I mentioned [over on this commit](https://github.com/facebook/IT-CPE/commit/5218f618d9d6b7ca4e8439dc4e414e8092eafcfc#commitcomment-39293782), I recommend leaving the resources with the same name, but the linux version needs a `provides` line added to it.

@btm what directory structure would you recommend, if the resources have the same names?

Currently we have

cpe_chrome
|- resources
  |- cpe_chrome_posix.rb (renamed from cpe_chrome.rb)
  |- cpe_chrome_win.rb

curious what your recommendation is. This works, and it's the Facebook convention so people who use Chef won't get confused, so if there's a more canonical way we should consider doing a full refactor to be consistent.

**Comment by btm** [comment] 2020-05-20 20:55
@michel-slm that is fine, but would drop the `resource_name` lines from the resources.

> lamont: if you haven’t set a resource_name yet, chef 16 will wire up a resource_name for the first provides it finds
> lamont: (there’s also the fallback default of cookbook_name+resource_file if nothing at all is found)

when you have both a `resource_name` and `provides` you're kind of telling chef what the resource is called twice.

**Comment by michel-slm** [comment] 2020-05-21 18:26
@btm oh interesting. Is that safe on all Chef versions? On the production side Facebook is still using Chef 13 (and trying to upgrade); on the client side we're on 15/16 but we want to keep our style guide consistent.
